### ISSUE TITLE
crash since last python update

### ISSUE THREAD

**Issue by dasnessie** [tstehr/RecipeMD#28]
Since I upgraded to `Python 3.9.1`, I get a crash when trying to use `recipemd-find` or `recipemd`:

```
$ recipemd-find tags
Traceback (most recent call last):
  File "/usr/bin/recipemd-find", line 5, in <module>
    from recipemd.cli.find import main
  File "/home/nessie/.local/lib/python3.9/site-packages/recipemd/cli/find.py", line 23, in <module>
    from recipemd.data import RecipeParser, Recipe
  File "/home/nessie/.local/lib/python3.9/site-packages/recipemd/data.py", line 12, in <module>
    import commonmark
  File "/home/nessie/.local/lib/python3.9/site-packages/commonmark/__init__.py", line 4, in <module>
    from commonmark.main import commonmark
  File "/home/nessie/.local/lib/python3.9/site-packages/commonmark/main.py", line 14, in <module>
    from commonmark.blocks import Parser
  File "/home/nessie/.local/lib/python3.9/site-packages/commonmark/blocks.py", line 5, in <module>
    from commonmark import common
  File "/home/nessie/.local/lib/python3.9/site-packages/commonmark/common.py", line 14, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

**Comment by tstehr** [comment]
Thanks for the report 👍 

This error is due to removal of the deprecated `html.parser.HTMLParser.unescape` in Python 3.9, which is used in our markdown parser  [commonmark.py](https://github.com/readthedocs/commonmark.py). This was already fixed in release 0.9.1 of commonmark.py (see readthedocs/commonmark.py#141), so we could fix this by updating our dependency. 

However, we also depend on [CommonMark-py-Extensions](https://github.com/GovReady/CommonMark-py-Extensions), which forces us to use commonmark.py 0.8.0. There is a pending pull request at GovReady/CommonMark-py-Extensions#5 that would widen the range of supported commonmark.py versions, but it has been pending for over a year.

I'll investigate possible workarounds to get `recpiemd` working in Python 3.9
